spring.application.name=mqtt-project

server.port=8080

#--------Configuration of distant MQTT-Server(Mosquitto)
mqtt.broker=sr-labor.ddns.net
mqtt.port=1883
mqtt.username=kalil.sacko@stud.hs-bochum.de
mqtt.password=018402955
mqtt.clientId=mqttx_b2fe6e0d
mqtt.statusTopic=Wago750/Status
mqtt.temperaturIsttopic=S7_1500/Temperatur/Ist
mqtt.temperaturSolltopic=S7_1500/Temperatur/Soll
mqtt.temperaturDifftopic=S7_1500/Temperatur/Differenz

# --- MongoDB ---
spring.data.mongodb.uri=mongodb://localhost:27017/mqttdb

#-------Saving logs-------
#logging.file.name=logs/mqttapp.log; logback-spring.xml in ressources already defined it
#logging.level.root=INFO
#logging.file.append=false

#------ Reduce the logs to the strict minimum------
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.mongodb=ERROR
# My own logs in my classes : TRACE < DEBUG < INFO < WARN < ERROR. Here only INFO < WARN < ERROR are taken into account
# in my package(that's to say : log.info, log.warn, and log.error; because the hierarchie is from low to above.
logging.level.bo.ms.informatik.mqttproject=INFO  



#------------Monitoring configuration-------------------

# Activate all the endpoints
management.endpoints.web.exposure.include=* 
# Activate default port
management.server.port=8080
#Compatible Format  Prometheus
management.prometheus.metrics.export.enabled=true